/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_mySql_Conn;


import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.MessageFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author shuvo
 */
public class Java_mySql_Conn extends javax.swing.JFrame {
    
   

   private static final String username = "root";
   private static final String password = "";
   private static final String dataconn = "jdbc:mysql://localhost:3306/java_sql?zeroDateTimeBehavior=convertToNull";
   Connection sqlConn = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   
   int g, i, id, deleteItem;
   
   
           
    public Java_mySql_Conn() {
        initComponents();
    }
    
    //================= DATABASE CONNECTION FUNCTION=============
   public void updateDB(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataconn, username , password);
            String query = "SELECT * FROM student_data";
            pst = sqlConn.prepareStatement(query);
            rs = pst.executeQuery();
            ResultSetMetaData sData = rs.getMetaData();
            
            g = sData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                Vector columnData = new Vector();
                for(i = 1; i<g;i++)
                {
                   columnData.add(rs.getString("ID"));
                    columnData.add(rs.getString("Student_ID"));
                    columnData.add(rs.getString("FName"));
                    columnData.add(rs.getString("LName"));
                    columnData.add(rs.getString("Address"));
                    columnData.add(rs.getString("Post_Code"));
                    columnData.add(rs.getString("Telephone"));
                }
                RecordTable.addRow(columnData);
                
            }
        
        }
        catch(Exception ex)
		{
			JOptionPane.showMessageDialog(null, ex);
		}
    }
    
    
    //=============== END DATABASE CONNECTION FUNCTION ==========

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        std_Fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        std_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        std_Lname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        std_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        std_Pcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        std_Tel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btn_display = new javax.swing.JButton();
        btn_addID = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Print = new javax.swing.JButton();
        btn_DEL = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Telephone");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 110, 30));

        std_Fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(std_Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 450, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Student ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, 30));

        std_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        std_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_idActionPerformed(evt);
            }
        });
        jPanel2.add(std_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 450, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("First Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 110, 30));

        std_Lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(std_Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 450, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 30));

        std_address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(std_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 450, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, 30));

        std_Pcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        std_Pcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                std_PcodeActionPerformed(evt);
            }
        });
        jPanel2.add(std_Pcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 450, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Post Code");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, 30));

        std_Tel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(std_Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 450, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Student ID", "First Name", "Last Name", "Address", "Post Code", "Telephone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 590, 170));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 690, 460));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_display.setText("Display");
        btn_display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_displayActionPerformed(evt);
            }
        });
        jPanel3.add(btn_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 160, 50));

        btn_addID.setText("ADD ID");
        btn_addID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addIDActionPerformed(evt);
            }
        });
        jPanel3.add(btn_addID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 160, 50));

        btn_Update.setText("UPDATE");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, 50));

        btn_Print.setText("PRINT");
        btn_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 160, 50));

        btn_DEL.setText("DELETE");
        btn_DEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DELActionPerformed(evt);
            }
        });
        jPanel3.add(btn_DEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, 50));

        btn_Reset.setText("RESET");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 160, 50));

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel3.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 160, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 230, 460));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("MYSQL CONNECTION");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 660, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 920, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void std_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_idActionPerformed

    private void std_PcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_std_PcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_std_PcodeActionPerformed

    private void btn_addIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addIDActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataconn, username , password);
            pst = sqlConn.prepareStatement("INSERT INTO student_data (Student_ID, FName, LName, Address, Post_Code, Telephone) values (?,?,?,?,?,?)");
            
            pst.setString(1, std_id.getText());
            pst.setString(2, std_Fname.getText());
            pst.setString(3, std_Lname.getText());
            pst.setString(4, std_address.getText());
            pst.setString(5, std_Pcode.getText());
            pst.setString(6, std_Tel.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            updateDB();
        }
        catch(ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
		}
        catch(SQLException ex)
		{
			java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
		}
    }//GEN-LAST:event_btn_addIDActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        std_id.setText("");
        std_Fname.setText("");
        std_Lname.setText("");
        std_address.setText("");
        std_Pcode.setText("");
        std_Tel.setText("");
        
    }//GEN-LAST:event_btn_ResetActionPerformed
        
    private JFrame frame;
    private void btn_displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_displayActionPerformed
        updateDB();
    }//GEN-LAST:event_btn_displayActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataconn, username , password);
            int row = jTable1.getSelectedRow();
            String value = (jTable1.getModel().getValueAt(row, 0).toString());
            pst = sqlConn.prepareStatement("UPDATE student_data SET Student_ID=?,FName=?,LName=?,Address=?,Post_Code=?,Telephone=? WHERE ID="+value  );
            
            pst.setString(1, std_id.getText());
            pst.setString(2, std_Fname.getText());
            pst.setString(3, std_Lname.getText());
            pst.setString(4, std_address.getText());
            pst.setString(5, std_Pcode.getText());
            pst.setString(6, std_Tel.getText());
            
            pst.executeUpdate();
            updateDB();
            JOptionPane.showMessageDialog(this, "Record updated");
        }
        catch(ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
		}
        catch(SQLException ex)
		{
			java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
		}
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        std_id.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        std_Fname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        std_Lname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        std_address.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        std_Pcode.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        std_Tel.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page, {0, number, integer}");
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
                {
                    System.err.format("No Printer Found", e.getMessage());
                }
    }//GEN-LAST:event_btn_PrintActionPerformed

    private void btn_DELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DELActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        try
        {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to delete item","Warning",JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION){
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataconn, username , password);
                pst = sqlConn.prepareStatement("DELETE From student_data WHERE ID = ? ");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Updated");
                updateDB();
                std_id.setText("");
                std_id.requestFocus();
                std_Fname.setText("");
                std_Lname.setText("");
                std_address.setText("");
                std_Pcode.setText("");
                std_Tel.setText("");
            
            }
            
        }
        catch(ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
		}
        catch(SQLException ex)
		{
			java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE,null, ex);
		}
    }//GEN-LAST:event_btn_DELActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","MYSQL Connector",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_mySql_Conn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java_mySql_Conn().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DEL;
    private javax.swing.JButton btn_Print;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_addID;
    private javax.swing.JButton btn_display;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField std_Fname;
    private javax.swing.JTextField std_Lname;
    private javax.swing.JTextField std_Pcode;
    private javax.swing.JTextField std_Tel;
    private javax.swing.JTextField std_address;
    private javax.swing.JTextField std_id;
    // End of variables declaration//GEN-END:variables

}
